version: '3'

volumes:
  dynu-updater-data:

services:
  dynu-updater:
    build: ./build/
    container_name: dynu-updater
    env_file: .env
    restart: always
    volumes:
      # TIMEZONE
      - /etc/localtime:/etc/localtime:ro
      # DATA
      - dynu-updater-data:/data
      # LOGS
      - ./logs/dynu-updater:/var/log/dynu-updater
      - ./logs/msmtp:/var/log/msmtp